development:
  adapter: mysql2
  encoding: utf8
  database: photo_tag_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: photo_tag_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
